notifications:
  email: false

language: node_js

node_js:
  - node

sudo: required

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash

script:
  - docker exec -it emscripten build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_personal_access_token  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
